// generated by optioner -type Person; DO NOT EDIT

// Please report issues and submit contributions at:
// http://github.com/akualab/optioner
// optioner is a project of AKUALAB INC.

package example

// Option type is used to set options in Person.
type optPerson func(*Person) optPerson

// Option method sets the options. Returns previous option for last arg.
func (t *Person) Option(options ...optPerson) (previous optPerson) {
	for _, opt := range options {
		previous = opt(t)
	}
	return previous
}

// Name sets a value for instances of type Person.
func Name(o string) optPerson {
	return func(t *Person) optPerson {
		previous := t.Name
		t.Name = o
		return Name(previous)
	}
}

// Age sets a value for instances of type Person.
func Age(o int) optPerson {
	return func(t *Person) optPerson {
		previous := t.Age
		t.Age = o
		return Age(previous)
	}
}
